# Generated by Django 3.2.5 on 2023-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('number_of_stu', models.PositiveSmallIntegerField()),
                ('total_expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
