# Generated by Django 3.2.5 on 2023-02-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_student', models.IntegerField(default=0)),
                ('privious_balance', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('net_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cordinator_id', models.IntegerField(default=0)),
                ('cordinator_name', models.CharField(max_length=50)),
                ('cordinator_deg', models.CharField(max_length=50)),
                ('cordinator_nid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='income',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='number_of_stu',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='total_expense',
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='item_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('cordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.cordinator')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('cordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.cordinator')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.course')),
                ('number_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.balance')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.withdraw'),
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='item_name',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.item'),
        ),
    ]
