# Generated by Django 3.2.5 on 2023-02-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_auto_20230206_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexpense',
            name='item_name',
            field=models.ForeignKey(default='item', on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.item'),
        ),
    ]
