# Generated by Django 3.2.5 on 2023-02-06 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_student', models.IntegerField(default=0)),
                ('privious_balance', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('net_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cordinator_id', models.IntegerField(default=0)),
                ('cordinator_name', models.CharField(max_length=50)),
                ('cordinator_deg', models.CharField(max_length=50)),
                ('cordinator_nid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('cordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.cordinator')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
                ('cordinator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.cordinator')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.course')),
                ('number_of_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.balance')),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.IntegerField(default=0)),
                ('item_quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.item')),
            ],
        ),
        migrations.AddField(
            model_name='balance',
            name='amount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseApp.withdraw'),
        ),
    ]
