# Generated by Django 3.2.5 on 2023-02-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_auto_20230208_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='net_balance',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='total_price',
        ),
    ]
