# Generated by Django 3.2.5 on 2023-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_auto_20230207_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='amount',
        ),
        migrations.AddField(
            model_name='balance',
            name='withdraw_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
