# Generated by Django 3.2.5 on 2023-02-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0003_auto_20230208_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number_of_student',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
