# Generated by Django 4.1.7 on 2023-02-24 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ExpenseApp", "0003_auto_20230212_0111"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="balance",
            name="privious_balance",
        ),
    ]
