# Generated by Django 3.2.5 on 2023-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_alter_student_number_of_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_durations',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(default='2023/01/01'),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default='2023/01/01'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
