# Generated by Django 3.2.5 on 2023-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0006_auto_20230208_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(default='2023-02-01'),
        ),
    ]
