# Generated by Django 3.2.5 on 2023-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0009_alter_student_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_date',
            field=models.DateField(default='2023-04-01'),
        ),
    ]
